# Generated by Django 3.1.7 on 2021-03-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, verbose_name='服务')),
                ('upload', models.FileField(upload_to='', verbose_name='上传文件')),
                ('message', models.CharField(max_length=200, verbose_name='水印数据')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '水印溯源',
                'verbose_name_plural': '水印溯源',
            },
        ),
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, verbose_name='服务')),
                ('upload', models.FileField(upload_to='', verbose_name='上传文件')),
                ('message', models.CharField(max_length=200, verbose_name='水印数据')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新增水印',
                'verbose_name_plural': '新增水印',
            },
        ),
    ]
