# Generated by Django 3.1.7 on 2021-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('server', models.CharField(max_length=200, verbose_name='服务器地址')),
                ('cpu', models.CharField(max_length=200, verbose_name='cpu')),
                ('memery', models.CharField(max_length=200, verbose_name='内存')),
                ('disk', models.CharField(max_length=200, verbose_name='硬盘')),
                ('status', models.CharField(max_length=200, verbose_name='状态')),
                ('token', models.CharField(max_length=200, verbose_name='服务器token')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '探针配置',
                'verbose_name_plural': '探针配置',
            },
        ),
    ]
