# Generated by Django 3.1.7 on 2021-03-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='cpu',
            field=models.CharField(default='100%', editable=False, max_length=200, verbose_name='cpu'),
        ),
        migrations.AlterField(
            model_name='online',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='online',
            name='disk',
            field=models.CharField(default='100%', editable=False, max_length=200, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='online',
            name='memery',
            field=models.CharField(default='100%', editable=False, max_length=200, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='online',
            name='status',
            field=models.IntegerField(choices=[(1, '未连接'), (2, '正常'), (3, '异常')], default='未连接', editable=False, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='online',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
