# Generated by Django 3.1.7 on 2021-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20210308_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
