# Generated by Django 3.1.7 on 2021-03-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_auto_20210308_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='disk2',
            field=models.CharField(default='100%', editable=False, max_length=200, verbose_name='剩余硬盘空间'),
        ),
        migrations.AlterField(
            model_name='online',
            name='disk',
            field=models.CharField(default='100%', editable=False, max_length=200, verbose_name='硬盘空间'),
        ),
    ]
