# Generated by Django 3.1.7 on 2021-03-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, verbose_name='服务')),
                ('upload', models.FileField(upload_to='', verbose_name='上传文件')),
                ('message', models.CharField(max_length=200, verbose_name='水印数据')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, verbose_name='服务')),
                ('upload', models.FileField(upload_to='', verbose_name='上传文件')),
                ('message', models.CharField(max_length=200, verbose_name='水印数据')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, verbose_name='服务')),
                ('upload', models.CharField(max_length=20, verbose_name='上传文件名')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, verbose_name='应用')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('token', models.CharField(max_length=20, verbose_name='token')),
                ('message', models.TextField(verbose_name='备注')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
