# Generated by Django 3.1.7 on 2021-03-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decoder',
            options={'verbose_name': '水印溯源', 'verbose_name_plural': '水印溯源'},
        ),
        migrations.AlterModelOptions(
            name='encoder',
            options={'verbose_name': '新增水印', 'verbose_name_plural': '新增水印'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': '水印日志', 'verbose_name_plural': '水印日志'},
        ),
        migrations.AlterModelOptions(
            name='manage',
            options={'verbose_name': '水印管理', 'verbose_name_plural': '水印管理'},
        ),
        migrations.AlterField(
            model_name='decoder',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='decoder',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='encoder',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='encoder',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='log',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='log',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='manage',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
